### ISSUE TITLE
Sample from a random vector

### ISSUE THREAD

**Issue by houxianxu** [zhangqianhui/vae-gan-tensorflow#7]
Thanks for the work.

I wonder how to use your code to generate random faces rather than reconstructing the input images.

**Comment by zhangqianhui** [comment]
Sampling using the decoding of vae? 
if you want to samping high-quality samples, you can use pg-gan.

https://github.com/zhangqianhui/progressive_growing_of_gans_tensorflow

**Comment by houxianxu** [comment]
@zhangqianhui Thanks for your reply. Yes, I want use the decoder of vae to generate some random images.

**Comment by zhangqianhui** [comment]
you can write a test function, which just builds the decoding model.
